export default {
  NEW_NODE: 'NEW_NODE',
  ADD_BLOCK: 'ADD_BLOCK',
  CHAIN_VALIDATION: 'CHAIN_VALIDATION',
  REJECT_BLOCK: 'REJECT_BLOCK',
  SYNC_NODES: 'SYNC_NODES',
  MAKE_CONCENSUS: 'MAKE_CONCENSUS',
  GET_LATEST: 'GET_LATEST',
  GET_BLOCKCHAIN: 'GET_BLOCKCHAIN',
  SET_BLOCKCHAIN: 'SET_BLOCKCHAIN',
  GET_BLOCKCHAIN_RESPONSE: 'GET_BLOCKCHAIN_RESPONSE',
  GET_LATEST_RESPONSE: 'GET_LATEST_RESPONSE',
};
