export default {
  NEW_NODE: 'NEW_NODE',
  GET_LATEST: 'GET_LATEST',
  GET_BLOCKCHAIN: 'GET_BLOCKCHAIN',
  SET_BLOCKCHAIN: 'SET_BLOCKCHAIN',
  GET_BLOCKCHAIN_RESPONSE: 'GET_BLOCKCHAIN_RESPONSE',
  GET_LATEST_RESPONSE: 'GET_LATEST_RESPONSE',
};
